version: '3.8'

services:
  playwright:
    build: .
    container_name: playwright_docker
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - DISPLAY=:99
      - PYTHONPATH=/app
    working_dir: /app

networks:
  playwright:
    driver: bridge